INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Berlin', 'Hauptstadt mit Brandenburger Tor und Spreeinsel.', 3645000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hamburg', 'Hansestadt mit weltberühmter Speicherstadt und Hafen.', 1841000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('München', 'Austragungsort des Oktoberfestes und Heimat des Englischen Gartens.', 1472000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Köln', 'Domstadt am Rhein mit ältestem deutschen U-Bahn-System.', 1086000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Frankfurt am Main', 'Finanzmetropole mit der Skyline von Mainhattan.', 753000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Stuttgart', 'Automobilstadt mit Aussicht vom Fernsehturm.', 634000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Düsseldorf', 'Mode- und Kunstzentrum mit der Königsallee.', 619000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Leipzig', 'Messestadt mit traditionsreichem Gewandhausorchester.', 605000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Dortmund', 'Einstige Stahlhochburg mit dem Signal Iduna Park.', 587000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Essen', 'Zeche Zollverein als UNESCO-Welterbe der Industriekultur.', 582000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bremen', 'Hansestadt mit den Bremer Stadtmusikanten und Rathaus.', 569000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Dresden', 'Barockstadt mit Frauenkirche und Elbpanorama.', 556000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hannover', 'Grüne Stadt mit den Herrenhäuser Gärten.', 538000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Nürnberg', 'Kaiserburg und Christkindlesmarkt prägen die Altstadt.', 518000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Duisburg', 'Verfügt über den größten Binnenhafen Europas.', 501000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bochum', 'Bergbaugeschichte trifft auf Musik im Bermudadreieck.', 365000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Wuppertal', 'Einzigartige Schwebebahn schwebt über die Wupper.', 355000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bielefeld', 'Universitätsstadt mit Sparrenburg und verstecktem Mythos.', 341000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bonn', 'Ehemalige Hauptstadt mit Beethoven-Haus.', 329000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Münster', 'Fahrradhauptstadt mit Prinzipalmarkt und Aasee.', 317000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Karlsruhe', 'Fächerförmiger Stadtgrundriss um das Schloss.', 313000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Mannheim', 'Quadratestadt mit Wasserturm und Popakademie.', 310000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Augsburg', 'Eine der ältesten Städte Deutschlands mit Fuggerhäusern.', 295000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Wiesbaden', 'Kurbadstadt mit Thermalquellen und Spielbank.', 279000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Gelsenkirchen', 'Veltins-Arena steht auf ehemaligem Zechengelände.', 259000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Mönchengladbach', 'Textilstadt mit Vitusdom und Borussia-Park.', 259000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Braunschweig', 'Löwenstadt mit Braunschweiger Dom und Burg Dankwarderode.', 248000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Chemnitz', 'Karl-Marx-Monument wacht über die Innenstadt.', 247000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Kiel', 'Fördestadt mit traditionsreicher Kieler Woche.', 246000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Aachen', 'Kaiserdom beherbergt Karls des Großen Thron.', 249000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Halle (Saale)', 'Geburtsstadt von Händel mit rot-weißen Salzbergen.', 239000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Magdeburg', 'Otto von Guericke und der Dom prägen die Elbstadt.', 238000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Freiburg im Breisgau', 'Sonnigste Großstadt mit Bächle in der Altstadt.', 232000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Krefeld', 'Samt- und Seidenstadt mit Zoo und Kaiser-Wilhelm-Museum.', 227000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Lübeck', 'Marzipanhauptstadt mit mittelalterlichem Holstentor.', 216000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Oberhausen', 'Centro-Einkaufszentrum entstand auf Stahlwerksfläche.', 210000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Erfurt', 'Krämerbrücke verbindet Fachwerk über der Gera.', 214000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Mainz', 'Medienstadt mit Dom und Fastnachtstradition.', 218000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Rostock', 'Hansehafen mit Zugang zur Ostsee und Warnemünde.', 209000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Kassel', 'Documenta-Stadt mit Bergpark Wilhelmshöhe.', 201000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hagen', 'Tor zum Sauerland mit Freilichtmuseum.', 188000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Saarbrücken', 'Landeshauptstadt mit barocker Ludwigskirche.', 179000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hamm', 'Berühmt für den gläsernen Elefanten im Maximilianpark.', 179000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Mülheim an der Ruhr', 'Ruhrtalradweg und Camera Obscura locken Besucher.', 171000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Potsdam', 'Schlösser und Gärten von Sanssouci sind UNESCO-Welterbe.', 183000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Ludwigshafen am Rhein', 'Industriestadt mit BASF-Stammwerk.', 172000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Oldenburg', 'Fahrradfreundliche Stadt mit Schlossgarten.', 170000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Leverkusen', 'BayArena und japanischer Garten liegen nah beieinander.', 165000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Osnabrück', 'Friedensstadt des Westfälischen Friedens von 1648.', 165000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Solingen', 'Klingenstadt mit Schneidwaren-Tradition.', 160000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Heidelberg', 'Universitätsstadt mit malerischer Schlossruine.', 160000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Herne', 'Cranger Kirmes zählt zu den größten Volksfesten.', 157000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Neuss', 'Römerstadt mit starkem Schützenfest.', 154000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Darmstadt', 'Mathildenhöhe als Jugendstilzentrum ausgezeichnet.', 161000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Paderborn', 'Quellen des Paderflusses sprudeln mitten in der Stadt.', 156000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Regensburg', 'Steinerne Brücke verbindet UNESCO-geschützte Altstadt.', 153000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Ingolstadt', 'Audi-Stammwerk und Donauufer prägen die Stadt.', 141000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Würzburg', 'Residenz mit Hofgarten ist barockes Juwel.', 128000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Fürth', 'Grüne Stadt mit historischem Rathaus und Kleeblatt im Wappen.', 128000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Ulm', 'Münster besitzt den höchsten Kirchturm der Welt.', 127000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Offenbach am Main', 'Lederwaren-Tradition und Design-Institut HfG.', 130000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Heilbronn', 'Weinstadt am Neckar mit experimenta-Wissenschaftszentrum.', 127000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Pforzheim', 'Goldstadt mit Schmuckmuseum und Schmuckindustrie.', 125000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Wolfsburg', 'Autostadt und Volkswagen-Stammwerk prägen das Bild.', 125000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Göttingen', 'Universitätsstadt mit Gänseliesel-Brunnen als Wahrzeichen.', 119000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bottrop', 'Erlebniswelt Alpincenter bietet längste Indoor-Skipiste.', 118000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Reutlingen', 'Tor zur Schwäbischen Alb mit enger Spreuerhofstraße.', 116000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Koblenz', 'Am Deutschen Eck treffen Rhein und Mosel aufeinander.', 114000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bremerhaven', 'Havenwelten mit Klimahaus und Auswandererhaus.', 114000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Recklinghausen', 'Ruhrfestspiele bringen Theater in die Bergbaustadt.', 111000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bergisch Gladbach', 'Papiermühlen-Tradition und Schloss Bensberg.', 111000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Jena', 'Optikstadt mit Zeiss-Tradition und Planetarium.', 110000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Trier', 'Älteste Stadt Deutschlands mit Porta Nigra.', 111000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Remscheid', 'Werkzeugstadt mit Deutschen Werkzeugmuseum.', 110000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Erlangen', 'Siemens-Standort und barocke Planstadt.', 113000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Moers', 'Grafschafter Musikkabarettfestival lockt Kleinkunstfreunde.', 104000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Siegen', 'Geburtsstadt Rubens mit Ober- und Unterstadt.', 102000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hildesheim', 'Dom und Michaeliskirche zählen zum UNESCO-Welterbe.', 103000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Salzgitter', 'Stahlschmiede mit Tagebau-Erbe am Salzgittersee.', 104000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Cottbus', 'Tor zum Spreewald mit Branitzer Park.', 100000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Kaiserslautern', 'Pfälzerwald-Nähe und Fritz-Walter-Stadion.', 100000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Gütersloh', 'Bekannt durch Medien- und Waschmittelkonzerne.', 101000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Witten', 'Zeche Nachtigall zeigt frühe Ruhrkohle-Geschichte.', 96000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Schwäbisch Gmünd', 'Staufische Stadt mit Remspark und Gold- und Silberforum.', 92000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Hanau', 'Brüder-Grimm-Stadt mit Goldschmiedetradition.', 99000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Villingen-Schwenningen', 'Doppelstadt mit Uhrenindustrie im Schwarzwald.', 86000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Marburg', 'Elisabethkirche dominiert die Studentenstadt.', 78000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Flensburg', 'Rumhandel und Hafen prägen die nördlichste Hafenstadt.', 90000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Lünen', 'Lippekraftwerk und Seepark erinnern an Bergbauzeit.', 87000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bayreuth', 'Berühmt für die Richard-Wagner-Festspiele.', 75000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Dessau-Roßlau', 'Bauhaus-Geburtsort mit Meisterhäusern.', 80000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Lüdenscheid', 'Phänomenta macht Physik erlebbar.', 73000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Düren', 'Papierstadt mit Annakirmes als Volksfest.', 92000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Ratingen', 'Altstadt mit Cromford-Tuchfabrik, älteste Fabrik auf dem Kontinent.', 88000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Esslingen am Neckar', 'Weinberge und Fachwerk bilden mittelalterliche Kulisse.', 95000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Tübingen', 'Neckarfront mit Stocherkahnfahrten und alter Uni.', 92000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Gießen', 'Botanischer Garten der Uni gilt als ältester Deutschlands.', 90000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Zwickau', 'Automobilgeschichte von Horch bis Trabant.', 88000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Konstanz', 'Bodenseestadt mit Konzilgebäude und Seestraße.', 85000, true);
INSERT INTO tutorials (title, description, einwohner, published) VALUES ('Bamberg', 'Sieben Hügel und Rauchbier prägen das Weltkulturerbe.', 78000, true);
